CREATE SEQUENCE SEQ_HORARIO_PICO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE T_HORARIO_PICO (
    id_pico INTEGER DEFAULT SEQ_HORARIO_PICO.NEXTVAL NOT NULL,
    ds_hora_inicio TIMESTAMP,
    ds_hora_termino TIMESTAMP,
    id_cruzamento NUMBER(6),
    CONSTRAINT id_pico_pk PRIMARY KEY (id_pico),
    CONSTRAINT id_cruzamento_fk FOREIGN KEY (id_cruzamento) REFERENCES T_CRUZAMENTO (id_cruzamento)
);