CREATE SEQUENCE SEQ_CRUZAMENTO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE T_CRUZAMENTO (
    id_cruzamento INTEGER DEFAULT SEQ_CRUZAMENTO.NEXTVAL NOT NULL,
    ds_logradouro_1 VARCHAR(50),
    ds_logradouro_2 VARCHAR(50),
    CONSTRAINT id_cruzamento_pk PRIMARY KEY (id_cruzamento_pk)
);

